use_frameworks!

platform :ios, '8.0'
install! 'cocoapods', :deterministic_uuids => false
target 'LYULibrary_Example' do
  pod 'LYULibrary', :path => '../'

  target 'LYULibrary_Tests' do
    inherit! :search_paths

    
  end
end
